<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.olexyn</groupId>
		<artifactId>min-root</artifactId>
		<version>25.1.0</version>
	</parent>
	<groupId>com.olexyn.min.http.server</groupId>
	<artifactId>min-http-server</artifactId>
	<version>0.2.0</version>
	<packaging>jar</packaging>
	<name>min-http-server</name>
	<description>Minimal embedded Jetty HTTP server.</description>
	<url>https://github.com/IO42630/min-http-server</url>
	<properties>
		<xx.jetty.version>12.0.39</xx.jetty.version>
	</properties>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.olexyn</groupId>
				<artifactId>min-bom</artifactId>
				<version>25.1.2</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-server</artifactId>
			<version>${xx.jetty.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jetty.ee10</groupId>
			<artifactId>jetty-ee10-servlet</artifactId>
			<version>${xx.jetty.version}</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<archive>
						<manifest>
							<mainClass>com.olexyn.min.http.server.MainExample</mainClass>
						</manifest>
					</archive>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
